version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports: 
      - 27017:27017
      
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 4040:80
      
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      DB_USERNAME: root
      DB_PASSWORD: pass
